# SPDX-License-Identifier: Apache-2.0
# Root CA Certificate — signed by the self-signed bootstrap issuer.
# Stored in certManagerNamespace so the CA ClusterIssuer can reference it.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ca.name }}
  namespace: {{ .Values.certManagerNamespace }}
  labels:
    app.kubernetes.io/name: zynax-cert-manager
    app.kubernetes.io/part-of: zynax
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  isCA: true
  commonName: {{ .Values.ca.name }}
  secretName: {{ .Values.ca.secretName }}
  duration: {{ .Values.ca.duration }}
  renewBefore: {{ .Values.ca.renewBefore }}
  issuerRef:
    name: {{ .Values.selfSignedIssuerName }}
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: ECDSA
    size: 256
