# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zynax.fullname" . }}
  labels:
    {{- include "zynax.labels" . | nindent 4 }}
data:
  grpc-port: {{ .Values.env.grpcPort | quote }}
  metrics-port: {{ .Values.env.metricsPort | quote }}
  log-level: {{ .Values.env.logLevel | quote }}
  temporal-host-port: {{ .Values.env.temporalHostPort | quote }}
  temporal-namespace: {{ .Values.env.temporalNamespace | quote }}
  temporal-task-queue: {{ .Values.env.temporalTaskQueue | quote }}
  task-broker-addr: {{ .Values.env.taskBrokerAddr | quote }}
  event-bus-addr: {{ .Values.env.eventBusAddr | quote }}
  active-engine: {{ .Values.env.activeEngine | quote }}
  {{- if eq .Values.env.activeEngine "argo" }}
  argo-server-url: {{ .Values.env.argoServerURL | quote }}
  argo-namespace: {{ .Values.env.argoNamespace | quote }}
  argo-workflow-template-ref: {{ .Values.env.argoWorkflowTemplateRef | quote }}
  argo-service-account: {{ .Values.env.argoServiceAccount | quote }}
  {{- end }}
  grpc-call-timeout-s: {{ .Values.env.grpcCallTimeoutS | quote }}
  max-activity-attempts: {{ .Values.env.maxActivityAttempts | quote }}
  liveness-threshold-s: {{ .Values.env.livenessThresholdS | quote }}
