// SPDX-License-Identifier: Apache-2.0

package check

import (
	"os"
	"path/filepath"
	"testing"
)

// writeFile creates path (with parents) under root and writes body.
func writeFile(t *testing.T, root, rel, body string) {
	t.Helper()
	p := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(p), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
}

// lockWithProtobuf renders a minimal uv.lock pinning protobuf at version.
func lockWithProtobuf(version string) string {
	return `version = 1

[[package]]
name = "structlog"
version = "24.1.0"

[[package]]
name = "protobuf"
version = "` + version + `"

[[package]]
name = "grpcio"
version = "1.75.1"
`
}

func gencodeStub(version string) string {
	return "# -*- coding: utf-8 -*-\n# Generated by the protocol buffer compiler.\n" +
		"# Protobuf Python Version: " + version + "\n\"\"\"Generated protocol buffer code.\"\"\"\n"
}

func TestProtobufRuntime_AllAtOrAbove(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, gencodeStubPath, gencodeStub("7.35.1"))
	writeFile(t, root, "agents/adapters/langgraph/uv.lock", lockWithProtobuf("7.35.1")) // equal
	writeFile(t, root, "agents/sdk/uv.lock", lockWithProtobuf("7.36.0"))                // above

	r, err := ProtobufRuntime(root)
	if err != nil {
		t.Fatalf("ProtobufRuntime: %v", err)
	}
	if r.Gencode != "7.35.1" {
		t.Errorf("gencode = %q, want 7.35.1", r.Gencode)
	}
	if len(r.Lockfiles) != 2 {
		t.Errorf("lockfiles = %v, want 2", r.Lockfiles)
	}
	if len(r.Violations) != 0 {
		t.Errorf("unexpected violations: %+v", r.Violations)
	}
}

func TestProtobufRuntime_BelowGencodeIsViolation(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, gencodeStubPath, gencodeStub("7.35.1"))
	writeFile(t, root, "agents/adapters/langgraph/uv.lock", lockWithProtobuf("7.35.0")) // below → the crash
	writeFile(t, root, "agents/sdk/uv.lock", lockWithProtobuf("7.35.1"))

	r, err := ProtobufRuntime(root)
	if err != nil {
		t.Fatalf("ProtobufRuntime: %v", err)
	}
	if len(r.Violations) != 1 {
		t.Fatalf("violations = %+v, want exactly 1", r.Violations)
	}
	v := r.Violations[0]
	if v.Runtime != "7.35.0" || v.Gencode != "7.35.1" || v.Lockfile != "agents/adapters/langgraph/uv.lock" {
		t.Errorf("violation = %+v", v)
	}
}

func TestProtobufRuntime_LockWithoutProtobufSkipped(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, gencodeStubPath, gencodeStub("7.35.1"))
	writeFile(t, root, "agents/adapters/none/uv.lock", "version = 1\n\n[[package]]\nname = \"httpx\"\nversion = \"0.27.0\"\n")

	r, err := ProtobufRuntime(root)
	if err != nil {
		t.Fatalf("ProtobufRuntime: %v", err)
	}
	if len(r.Violations) != 0 {
		t.Errorf("a lock without protobuf must not violate: %+v", r.Violations)
	}
}

func TestProtobufRuntime_MissingGencodeHeaderErrors(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, gencodeStubPath, "# no version header here\n")
	writeFile(t, root, "agents/sdk/uv.lock", lockWithProtobuf("7.35.1"))
	if _, err := ProtobufRuntime(root); err == nil {
		t.Error("expected an error when the gencode header is absent")
	}
}

func TestCompareDottedVersions(t *testing.T) {
	cases := []struct {
		a, b string
		want int
	}{
		{"7.35.1", "7.35.1", 0},
		{"7.35.0", "7.35.1", -1},
		{"7.36.0", "7.35.1", 1},
		{"7.35", "7.35.1", -1}, // missing patch treated as 0
		{"8.0.0", "7.99.99", 1},
	}
	for _, c := range cases {
		if got := compareDottedVersions(c.a, c.b); got != c.want {
			t.Errorf("compareDottedVersions(%q,%q) = %d, want %d", c.a, c.b, got, c.want)
		}
	}
}
