# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zynax.fullname" . }}
  labels:
    {{- include "zynax.labels" . | nindent 4 }}
data:
  grpc-port: {{ .Values.env.grpcPort | quote }}
  metrics-port: {{ .Values.env.metricsPort | quote }}
  log-level: {{ .Values.env.logLevel | quote }}
