# SPDX-License-Identifier: Apache-2.0
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "zynax.fullname" . }}
  labels:
    {{- include "zynax.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "zynax.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: {{ .Values.env.grpcPort }}
          protocol: TCP
        - port: {{ .Values.env.metricsPort }}
          protocol: TCP
  egress:
    # DNS resolution
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
