# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zynax.fullname" . }}
  labels:
    {{- include "zynax.labels" . | nindent 4 }}
data:
  grpc-port: {{ .Values.env.grpcPort | quote }}
  registry-addr: {{ .Values.env.registryAddr | quote }}
  log-level: {{ .Values.env.logLevel | quote }}
  grpc-call-timeout-s: {{ .Values.env.grpcCallTimeoutS | quote }}
