#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Generate a code-review Workflow manifest for a GitHub PR's diff, for the demo's
# `make demo PR=<N>` mode. READ-ONLY: it only runs `gh pr diff` — it never writes
# to the PR or the issue. The diff is inlined into the `codereview` capability
# prompt; the workflow runs to a terminal state and the model's review is surfaced
# by `zynax result`.
#
# Usage:
#   tools/pr-review-workflow.sh <pr-number> [repo]   > workflow.yaml
#
# `repo` is an optional OWNER/NAME passed to `gh -R`; defaults to the gh-resolved
# repository for the current directory.
set -euo pipefail

PR="${1:-}"
REPO="${2:-}"

if [ -z "$PR" ]; then
  echo "usage: $0 <pr-number> [owner/repo]" >&2
  exit 2
fi
if ! command -v gh >/dev/null 2>&1; then
  echo "error: 'gh' (GitHub CLI) is required for PR review mode — https://cli.github.com" >&2
  exit 3
fi

gh_args=(pr diff "$PR")
[ -n "$REPO" ] && gh_args+=(-R "$REPO")

# Read-only fetch of the PR diff.
if ! diff="$(gh "${gh_args[@]}" 2>/dev/null)"; then
  echo "error: could not fetch diff for PR #$PR (is it a valid PR number?)" >&2
  exit 4
fi
if [ -z "$diff" ]; then
  echo "error: PR #$PR has an empty diff" >&2
  exit 4
fi

# Emit the workflow. The diff is indented 14 spaces to sit inside the YAML block
# scalar under `prompt: |`. The capability name has no underscore on purpose
# (the engine derives `codereview.completed`; the compiler rejects underscores).
cat <<'HEAD'
# SPDX-License-Identifier: Apache-2.0
# Generated by tools/pr-review-workflow.sh — read-only code review of a PR diff.
kind: Workflow
apiVersion: zynax.io/v1

metadata:
HEAD
printf '  name: code-review-pr-%s\n' "$PR"
cat <<'MID'
  namespace: demo
  version: "1.0.0"
  annotations:
    description: "Read-only LLM code review of a GitHub PR diff."

spec:
  initial_state: review

  states:
    review:
      actions:
        - capability: codereview
          input:
            prompt: |
              You are a senior code reviewer. Review the following git diff and
              reply with a short, numbered list of concrete issues (correctness,
              security, edge cases). Be specific and cite the function name. End
              with an APPROVE or REQUEST-CHANGES verdict.

              ```diff
MID
printf '%s\n' "$diff" | sed 's/^/              /'
cat <<'TAIL'
              ```
      on:
        - event: codereview.completed
          goto: done

    done:
      type: terminal
TAIL
