# SPDX-License-Identifier: Apache-2.0
# ClickHouse — columnar store for Uptrace traces/metrics/logs (container-internal).
{{- if .Values.enabled }}
{{- if .Values.clickhouse.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "uptrace.fullname" . }}-clickhouse
  labels:
    {{- include "uptrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.clickhouse.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.clickhouse.persistence.size }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptrace.fullname" . }}-clickhouse
  labels:
    {{- include "uptrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  type: ClusterIP
  selector:
    {{- include "uptrace.selectorLabels" (dict "ctx" . "component" "clickhouse") | nindent 4 }}
  ports:
    - name: native
      port: {{ .Values.clickhouse.port }}
      targetPort: native
    - name: http
      port: {{ .Values.clickhouse.httpPort }}
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uptrace.fullname" . }}-clickhouse
  labels:
    {{- include "uptrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "uptrace.selectorLabels" (dict "ctx" . "component" "clickhouse") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "uptrace.selectorLabels" (dict "ctx" . "component" "clickhouse") | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: clickhouse
          image: "{{ .Values.clickhouse.image.repository }}:{{ .Values.clickhouse.image.tag }}"
          imagePullPolicy: {{ .Values.clickhouse.image.pullPolicy }}
          env:
            - name: CLICKHOUSE_DB
              value: {{ .Values.clickhouse.database | quote }}
            - name: CLICKHOUSE_SKIP_USER_SETUP
              value: "1"
          ports:
            - name: native
              containerPort: 9000
            - name: http
              containerPort: 8123
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 30
            failureThreshold: 3
          resources:
            {{- toYaml .Values.clickhouse.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
      volumes:
        - name: data
          {{- if .Values.clickhouse.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "uptrace.fullname" . }}-clickhouse
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
