# SPDX-License-Identifier: Apache-2.0
# Postgres — Uptrace metadata store (container-internal; password from Secret).
{{- if .Values.enabled }}
{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "uptrace.fullname" . }}-postgres
  labels:
    {{- include "uptrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.postgres.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptrace.fullname" . }}-postgres
  labels:
    {{- include "uptrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "uptrace.selectorLabels" (dict "ctx" . "component" "postgres") | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uptrace.fullname" . }}-postgres
  labels:
    {{- include "uptrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "uptrace.selectorLabels" (dict "ctx" . "component" "postgres") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "uptrace.selectorLabels" (dict "ctx" . "component" "postgres") | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.uptrace.existingSecret }}
                  key: {{ .Values.uptrace.secretKeys.pgPassword }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgres
              containerPort: 5432
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.user }}"]
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.user }}"]
            periodSeconds: 30
            failureThreshold: 3
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          {{- if .Values.postgres.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "uptrace.fullname" . }}-postgres
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
